### ISSUE TITLE
Module build error

### ISSUE THREAD

**Issue by iamonuwa** [maiyaporn/angular2-wizard#46]
`ERROR in ./node_modules/angular2-wizard/src/wizard-step.component.ngfactory.ts
Module build failed: Error: /home/isaac/apps/app/live/node_modules/angular2-wizard/src/wizard-step.component.ngfactory.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/isaac/apps/app/live/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:656:23)
    at plugin.done.then (/home/isaac/apps/app/live/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
 @ ./src/app/app/setup/setup.component.ngfactory.js 13:0-99
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./node_modules/angular2-wizard/src/wizard.component.ngfactory.ts
Module build failed: Error: /home/isaac/apps/app/live/node_modules/angular2-wizard/src/wizard.component.ngfactory.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/isaac/apps/app/live/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:656:23)
    at plugin.done.then (/home/isaac/apps/app/live/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
 @ ./src/app/app/setup/setup.component.ngfactory.js 11:0-94
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts`

Currently running on angular -cli 1.6.6
angular2-wizard 0.4.0

**Comment by hjnp** [comment]
i have the same issue! @maiyaporn can help with this please ? 
 `Angular CLI: 1.6.8
Node: 8.9.4
OS: linux x64
Angular: 5.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

angular/cli: 1.6.8
angular-devkit/build-optimizer: 0.0.42
angular-devkit/core: 0.0.29
angular-devkit/schematics: 0.0.52
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.9.8
schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0`

**Comment by hjnp** [comment]
@iamonuwa I was going to ask if you could compile the angular app  for production?  if you found the issue for this please give-me some  clues about the error, i do the same, thx!

**Comment by hjnp** [comment]
this issue is strange because i can compile to dev but for prod i can't!

**Comment by hjnp** [comment]
@iamonuwa i change to this config and now compiles to prod. 

`"dependencies": {
    "@angular/animations": "^4.4.6",
    "@angular/common": "^4.4.6",
    "@angular/compiler": "^4.4.6",
    "@angular/core": "^4.4.6",
    "@angular/forms": "^4.4.6",
    "@angular/http": "^4.4.6",
    "@angular/platform-browser": "^4.4.6",
    "@angular/platform-browser-dynamic": "^4.4.6",
    "@angular/router": "^4.4.6",
    "angular-wizard": "^1.1.1",
    "angular2-wizard": "^0.4.0",
    "bootstrap": "^4.0.0",
    "cities.json": "^1.1.2",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "fontawesome": "^4.7.2",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "1.6.8",
    "@angular/compiler-cli": "^4.4.6",
    "@angular/language-service": "^4.4.6",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.4.0"
  }`



maybe its not compatible with angular 5

**Comment by roblawford** [comment]
Hi there, any update on this error??  Need angular 5 compatibility

**Comment by themounthead** [comment]
I can propose a temporary fix to the issue. Open the **node_modules/angular2-wizard/package.json** file and include this -

`"typings": "./dist/index.d.ts"`

That should resolve the error and allow you to build the App with --aot. Works with Angular 5.x as well.

**Comment by hjnp** [comment]
Yes, i changed the project for angular v 4, and its compiling.

**Comment by sanjay-zymr** [comment]
Hey @hjnp Can you please push the code for the same? I am also using angular 5 and facing the same issue.

**Comment by iamonuwa** [comment]
Thanks @hjnp @maiyaporn

**Comment by maddy81818181** [comment]
when I updated angular wizard to 4.4 it resolved. guys when I have pushed my code to dev it throws "f.ngOnInit is not a function" but locally it is working fine.. any suggestions on that If someone come across the error too/?

**Comment by ParshuReddy** [comment]
Hi, i have included "typings": "./dist/index.d.ts",in package.json and tried to build it using ng build --aot, but still i'm getting the error and i'm using Angular : 5.27, angular-cli:1.7.0, node: 6.11.4. Can you help me out fixing this issue.

**Comment by ParshuReddy** [comment]
@iamonuwa , i have included "typings": "./dist/index.d.ts",in package.json and tried to build it using ng build --aot, but still i'm getting the error and i'm using Angular : 5.27, angular-cli:1.7.0, node: 6.11.4. Can you help me out fixing this issue.

**Comment by ParshuReddy** [comment]
@iamonuwa , i have included "typings": "./dist/index.d.ts",in package.json and tried to build it using ng build --aot, but still i'm getting the error and i'm using Angular : 5.27, angular-cli:1.7.0, node: 6.11.4. Can you help me out fixing this issue.

**Comment by ynnr85** [comment]
any update about it please?

**Comment by themounthead** [comment]
Since the existing package doesn't conform to the new Angular lib specification, we need to instruct the cli to build it from source, which needs to be specified in the tsconfig.app.json (within the **src** folder)

`
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "types": []
  },
  "include": [
    "./**/*.ts",
    "../node_modules/angular2-wizard/index.ts",
    "../node_modules/angular2-wizard/src/**/*.ts"
  ],
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts",
    "../node_modules/angular2-wizard/src/**/*.spec.ts"
  ]
}
`

This is compatible with angular 6.0.x using `build --prod`

**Comment by argutierrez00** [comment]
Thanks @themounthead . This solved the issue.

**Comment by RA344710** [comment]
@themounthead : { "extends": "../tsconfig.json", "compilerOptions": { "outDir": "../out-tsc/app", "module": "es2015", "types": [] }, "include": [ "./**/*.ts", "../node_modules/angular2-wizard/index.ts", "../node_modules/angular2-wizard/src/**/*.ts" ], "exclude": [ "src/test.ts", "**/*.spec.ts", "../node_modules/angular2-wizard/src/**/*.spec.ts" ] } its not working for me. it showing errors while ng serve only. And I tried "typings": "./dist/index.d.ts" this one working, but page is not loading / respond properly when double click on text fields it working good. In production UI it showing ERROR TypeError: f.ngOnInit is not a function. what is the problem please do needful.

**Comment by themounthead** [comment]
@RA344710 the mentioned solution is only for the `build --prod` option. For simply serving the Angular App, you don't need to update the tsconfig.json. It should work as is.

**Comment by joaolori** [comment]
I am facing same error on build --aot and --prod with ANGULAR 5.
I have tried all solutions here without any sucess...
 
Anyone can help on this?

**Comment by RA344710** [comment]
In production(dist deployment) angula2-wizard page is not loading properly, It showing error like this: ERROR TypeError: f.ngOnInit is not a function. Plz help on this.

**Comment by hemanth-sp** [comment]
> "typings": "./dist/index.d.ts"

in which line?????????????????????????/

**Comment by maddy81818181** [comment]
You can copy whole source code to your project. You will not have any Issues.

**Comment by hemanth-sp** [comment]
You can copy whole source code to your project. boss better do you have vedio?? help me please..

only two component source codes?

**Comment by maddy81818181** [comment]
Hi,

    Sorry I cannot help you on that, Just company security reasons. You have two files wizard file and wizard-step file which you can get from Github. Then you can access the component directly from your project itself.

**Comment by hemanth-sp** [comment]
thank you i downloaded from git-hub code now its working fine in prod build

**Comment by maddy81818181** [comment]
Cool
